### ISSUE TITLE
Юзать RAW SQL

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-Go#109]
использовать db.ORM.Exec(...) вместо db.ORM.Select(..).Where(..), etc.

**Comment by UncleAndy** [comment]
Может тогда лучше отказаться от gorm вообще?

**Comment by kenrube** [comment]
> Может тогда лучше отказаться от gorm вообще?

Пока не вариант. Маппинг в структуры у горма хороший. Например, не надо беспокоиться насчет nullable-полей: если использовать обычные типы (не Sql...) для nullable-значений, то query возвращает неадекватные результаты.
