### ISSUE TITLE
Тесты запросов к базе

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Go#126]
Предлагаю заюзать https://github.com/DATA-DOG/go-sqlmock

**Comment by geor-kasapidi** [comment]
имхо, нам нужно тестить не саму базу, а слой ДБ логики и проверять что модели возвращаются те что нужно

**Comment by kenrube** [comment]
Это я и имел в виду, mea culpa. Библиотечка не в тему

**Comment by kenrube** [comment]
Как вариант, можно действительно использовать sqlite в [in-memory mode](https://github.com/mattn/go-sqlite3#dsn-examples), предзаполнять ее и прогонять тесты. Не думаю, что они настолько существенно различаются с MySQL, чтобы это сказалось на наших примерах

**Comment by geor-kasapidi** [comment]
ага, я могу сначала сделать тесты для sqlr в таком режиме - посмотрим как работает. И после применить для тестов запросов. Нужна будет только импортнуть схему БД без данных в виде скрипта - чтобы мозги не делать.

**Comment by geor-kasapidi** [comment]
С sqlite есть проблема - го-драйвер не выдает информацию о типах (хотя с Go 1.8 это насколько я понял является контрактом), соответственно sqlr к нему не подойдет. Плюс sqlite - cgo. Поэтому надо таки будет тестить на mysql.

**Comment by kenrube** [comment]
https://github.com/FantLab/FantLab-Go/pull/134
