### ISSUE TITLE
Добавить лимитер на запросы

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-Go#164]

**Comment by geor-kasapidi** [comment]
https://www.alexedwards.net/blog/how-to-rate-limit-http-requests

**Comment by geor-kasapidi** [comment]
вероятно можно регулировать все через нгинкс

**Comment by g0ddest** [comment]
https://www.nginx.com/blog/rate-limiting-nginx/

**Comment by geor-kasapidi** [comment]
разрулим через нгинкс
