### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-Go#166]
https://phrase.com/blog/posts/internationalization-i18n-go/

**Comment by geor-kasapidi** [comment]
кажется что оно вообще никому не надо)

**Comment by kenrube** [comment]
В Go-API, скорее всего, оно и не нужно. На самом сайте в интерфейсе и прочем - там да. Но и там эта задача висит мертвым грузом уже несколько лет.
