### ISSUE TITLE
Файловое логирование

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Go#17]
Помимо вывода в консоль, было бы неплохо параллельно писать и в файл. 
Gin умеет это из [коробки](https://github.com/gin-gonic/gin#how-to-write-log-file), однако попытка писать одновременно и в файл и в консоль приводит к пропаданию цвета в консольном output. Если же force-нуть цвет в консольных логах, в файловых он тоже попадает в выдачу (и он там совершенно лишний). Похоже на баг.
С Gorm придется повозиться подольше

**Comment by geor-kasapidi** [comment]
может просто для дебага будем писать в консоль с цветом а для релиза в файл без цвета? ну и как я понимаю файловый вывод так же можно организовать просто перенаправив поток вывода - поправьте если я ошибаюсь

**Comment by kenrube** [comment]
> поправьте если я ошибаюсь

Там так и делается. Проблема не в перенаправлении вывода, а в том, что вывод должен быть разный в консоль (с цветом) и в файл (без цвета - а цвет задается в go особыми строковыми литералами, так что вывод нехило захламляется). Ну и таки я все ж хочу видеть логи в прямом эфире на проде

**Comment by geor-kasapidi** [comment]
ну и еще ДЕРЗКАЯ идея:

```
if RELEASE {
       router.Use(prometeus.Logger...
} else {
       router.Use(console.Logger...
}
```

я не очень шарю, но вроде прометеус используется для всяких таких вещей на проде :)

**Comment by geor-kasapidi** [comment]
хотя прометеус больше про метрики. Зато нашел в интернетах вот такой вот пакет - https://github.com/sirupsen/logrus

**Comment by kenrube** [comment]
Прометеус - он про временные метрики, для логов обычно юзается что-нибудь другое, стек ELK, например. Задача в том, чтобы по логам что в дебаге, что в проде можно было свободно искать при необходимости. Поресерчу этот вопрос попозже

**Comment by geor-kasapidi** [comment]
почитал про ELK - выглядит так, что такую систему надо поднимать на весь сервис)

**Comment by kenrube** [comment]
Имеешь в виду, на Perl тоже?

**Comment by geor-kasapidi** [comment]
как будто бы да - типа графана с прометеусом для метрик, а эластик кибана - для логов

**Comment by UncleAndy** [comment]
Если позволите, я тоже вставлю свои пять копеек по этому поводу.

Я изначально тоже сильно напрягся из-за того, что логирование в go идет в консоль. И хомичил с тем что-бы переделать его на запись в файл. В итоге, при использовании докера оказалось что файл нафиг не нужен и средства докера вполне успешно позволяют посмотреть все что нужно.

Может имеет смысл еще раз подумать нужно-ли оно?

**Comment by geor-kasapidi** [comment]
а по какому принципу оно работает? докер перехватывает потоки вывода и ошибок и записывает сам во что-то свое? я с докером не знаком (но планирую)

**Comment by UncleAndy** [comment]
> а по какому принципу оно работает? докер перехватывает потоки вывода и ошибок и записывает сам во что-то свое? я с докером не знаком (но планирую)

В тонкостях реализации я не разбирался, но по команде docker logs можно довольно эффективно смотреть эти логи. В том числе, в текущем режиме (опция "-f" как в tail) или за определенный период. В kubernates есть более продвинутые методики работы с этим логом, вроде-бы.

Хотя, вот сейчас вспоминаю что да - все-таки, эти логи хранятся в каких-то файлах, т.к. в одном из проектов мне приходилось их тереть при переполнении дисков. Докер был коряво настроен.

**Comment by geor-kasapidi** [comment]
хм, ну вообще звучит все очень здраво - на работе наши ребятки тоже живут с докер логами :) покопаю на недельке в это направлении

**Comment by kenrube** [comment]
Мой вопрос не в логах в докере - это ок. Меня больше интересует логирование на продакшене, с возможностью поиска, агрегации, сортировки и тд. Потому что если вылезет какая-то проблема, хотелось бы понимать ее источник

**Comment by geor-kasapidi** [comment]
@kenrube grep + tail -f :)

**Comment by UncleAndy** [comment]
> Мой вопрос не в логах в докере - это ок. Меня больше интересует логирование на продакшене, с возможностью поиска, агрегации, сортировки и тд. Потому что если вылезет какая-то проблема, хотелось бы понимать ее источник

А на продакшене оно будет работать НЕ в докере?

**Comment by kenrube** [comment]
Я, конечно, не большой спец в докере, но пока что я и без него спокойно могу все запустить. У нас вроде нет моря внешних зависимостей, все, что нужно, упаковано в самом бинарнике

**Comment by UncleAndy** [comment]
> Я, конечно, не большой спец в докере, но пока что я и без него спокойно могу все запустить. У нас вроде нет моря внешних зависимостей, все, что нужно, упаковано в самом бинарнике

Ну, если так рассуждать, то у вас и без golang сайт нормально работает. :)))

**Comment by kenrube** [comment]
Ну, пока что в этой репе недостающие куски API, а не рефакторинг, так что неа :)

**Comment by geor-kasapidi** [comment]
> Я, конечно, не большой спец в докере, но пока что я и без него спокойно могу все запустить. У нас вроде нет моря внешних зависимостей, все, что нужно, упаковано в самом бинарнике

даже стдлиб?

**Comment by UncleAndy** [comment]
> > Я, конечно, не большой спец в докере, но пока что я и без него спокойно могу все запустить. У нас вроде нет моря внешних зависимостей, все, что нужно, упаковано в самом бинарнике
> 
> даже стдлиб?

На golang можно сделать бинарник, который, вроде, даже от stdlib не зависит. Поэтому его так удобно именно в докере запускать в минимальном контейнере.

**Comment by kenrube** [comment]
К самому issue это все уже давно не относится.

Я, честно, не очень понимаю, зачем тут на данный момент нужен докер и какой от него профит. Чтоб бинарник заработал, в образ, насколько я понимаю, требуется засунуть еще и минимальный образ операционки. Только этого для полного счастья и не хватало - независимого бинарника внутри операционки внутри докера внутри другой операционки на сервере, когда он преспокойно и на самом сервере работает

**Comment by kenrube** [comment]
> даже стдлиб?

И даже от libc он по большей части не зависит. Есть некоторые исключения - типа dns-резолвинга, но это чинится сборкой с переменной окружения `CGO_ENABLED=0`

**Comment by UncleAndy** [comment]
> Я, честно, не очень понимаю, зачем тут на данный момент нужен докер и какой от него профит.

Профит от докера не только в том, что он создает для приложения контролируемое окружение, но и в том, что он создает для приложения ИЗОЛИРОВАННОЕ окружение. В случае взлома приложения хакеры не пройдут дальше контейнера. Что исправляется просто рестартом контейнера.

Кроме того, профит в том, что при использовании оркестратора (типа kubernates) намного проще распределять нагрузку по нескольким серверам или даже в пределах одного сервера. Ну и, само собой, контроль докера за контейнером и автоматический его рестрат при падении тоже приятен.

**Comment by kenrube** [comment]
Другой разговор :) @geor-kasapidi поразбираешься?

**Comment by UncleAndy** [comment]
> Другой разговор :) @geor-kasapidi поразбираешься?

@geor-kasapidi будут вопросы - обращайся ко мне в Телеграме.

**Comment by kenrube** [comment]
@UncleAndy чего сам не присоединишься к разработке?

**Comment by UncleAndy** [comment]
> @UncleAndy чего сам не присоединишься к разработке?

Я-бы с радостью, но нагрузка на основной работе не позволяет. :(

**Comment by kenrube** [comment]
Понятно :) Надумаешь - умелые руки всегда пригодятся

**Comment by geor-kasapidi** [comment]
@UncleAndy ок, если что - спрошу) спасибо за предложение!
@kenrube ага - поиграюсь с докером) ну и насколько я понял докер не содержит ОС - он работает поверх линукса, но изолирует твое приложение от всего остального

**Comment by kenrube** [comment]
Одна просьба - регистрируй, в случае чего, все на fantlab, а не на себя. Тот же аккаунт в DockerHub, например

**Comment by geor-kasapidi** [comment]
кк
