### ISSUE TITLE
Сохранение аттача сообщения

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Go#182]

**Comment by geor-kasapidi** [comment]
нужно подумать как правильно сохранять аттачи - я предлагал min.io поднять + нужен некий фронт перед ней который будет отвечать именно сохранять файлики) то есть появляется второй сервис который будет отвечать за работу с файлами - я думаю в таком ключе

**Comment by kenrube** [comment]
Поэтому и вынес в отдельную задачу - копипастить код сохранения аттачей из перлового метода смысла нет
