### ISSUE TITLE
Добавить кэш для сессий

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-Go#22]
Для дебага подставлять вместо редиса обычную хэш табличку

**Comment by kenrube** [comment]
Кстати, в Redis [есть](https://redislabs.com/redis-best-practices/counting/hyperloglog/) поддержка [HyperLogLog](https://habr.com/ru/post/119852/). В нашем случае это позволяет ускорить подсчет количества уникальных посетителей, например

**Comment by kenrube** [comment]
https://github.com/FantLab/FantLab-Go/pull/92
