### ISSUE TITLE
Список сообщений в теме форума не возвращает последнее сообщение

### ISSUE THREAD

**Issue by HombreTech** [FantLab/FantLab-Go#242]
Для примера:
http://dev3.fantlab.org:4242/v1/topics/1707

Первые два сообщения должны быть от ilyakokhan

**Comment by kenrube** [comment]
Переделать вычисление `offset`. Схема с `finalOffset` выглядит как магия

**Comment by kenrube** [comment]
Сообщение не отдается потому, что поле `number` не пересчитывается кроном на dev3.
