### ISSUE TITLE
Автогенерация документации к endpoint-ам

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Go#4]
[Генератор](https://github.com/swaggo/swag), [пример](https://github.com/swaggo/swag/tree/master/example/celler)

**Comment by Mazian** [comment]
а где прочитать саму сгенеренную и обновляемую документацию? какой-то запрос на самом сервере?

**Comment by kenrube** [comment]
Как появится - на .../swagger/index.html

**Comment by geor-kasapidi** [comment]
я тут подумал, что у нас, благодаря конкретным return из эндпойнтов (статус + прото модель) есть возможность более глубокой автоматизации. Мы можем спокойно обходить AST и смотреть на то что возвращается. Однако есть проблема с тем, как формализовать входные параметры, которые берем из реквеста.. я пока не придумал хорошего решения.

**Comment by kenrube** [comment]
Что, если тоже задавать модель, которую использовать и для парсинга параметров из реквеста, и для документирования?

**Comment by geor-kasapidi** [comment]
непонятно как универсализировать сигнатуру эндпойнта

**Comment by kenrube** [comment]
https://github.com/FantLab/FantLab-Go/pull/157
