### ISSUE TITLE
Персонализация блогов

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Go#50]
- количество непрочитанных статей в рубриках
- состояния подписок на рубрики
- количество непрочитанных статей в авторских колонках
- состояния подписок на авторские колонки
- инкремент счетчика количества просмотров при загрузке статьи
- пометка диапазона комментариев как прочитанных при загрузке
- пометка статьи как прочитанной при загрузке
- админам должны быть видны черновики статей (is_opened=0)
- флаг доступности редактирования комментариев

**Comment by kenrube** [comment]
TODO: разбить на отдельные задачи

**Comment by HombreTech** [comment]
Похоже, нужен будет еще флаг вроде `is_liked` для статьи в блоге

**Comment by kenrube** [comment]
Closed due to inactivity
