### ISSUE TITLE
Предложения по общедоступному API блогов и форумов

### ISSUE THREAD

**Issue by grbIzl** [FantLab/FantLab-Go#51]
Предложения по https://github.com/FantLab/FantLab-API/blob/master/Docs/prototype.md

- Унифицировать отдачу пользователя во всех методах в виде:
user: {                  # автор
         id: Int,             # id пользователя
         login: String,       # логин пользователя
         gender: String,      # пол пользователя (MALE или FEMALE)
         avatar: String       # ссылка на аватар пользователя
},

- В поле last_message во всех методах добавить само сообщение или его превью (первые сколько-то символов)

**Comment by Mazian** [comment]
1.
Форум
GET /v1/forums/{id}?page={page}&limit={limit}
http://go.dev3.fantlab.org:4242/v1/forums/3?page=1

параметр page предлагается не делать обязательным. по умолчанию = 1
это относится ко всем роутам.

2.
Некорректный лимит
{
    error_code: 400,
    message: "incorrect limit: {limit}"
}

а до каких пределах разрешен лимит? 10000 ?
http://go.dev3.fantlab.org:4242/v1/topics/2555?page=1   
предлагаю в 5..50 разрешать . 
если вообще его давать

3.
Тема
GET /v1/topics/{id}?page={page}&limit={limit}
http://go.dev3.fantlab.org:4242/v1/topics/10633?page=1

а выдаче нет инфы о названи топика и в какой подфоруме он находится.


4.
![image](https://user-images.githubusercontent.com/5379752/60604881-33834280-9dc1-11e9-9f06-d87d03345847.png)
Блоги

не хватает роута на "свежие посты" (по умолчанию - ключевых рубрик, но можно и свои фильтры передать)   
и выборка "самые интересные посты" . 
(может и один урл, просто разные доп.аргумент - ?order=news && pop)

**Comment by kenrube** [comment]
Пара багов:
1. Ошибка парсинга `minus_count` в сообщениях форума (значение отрицательное)
2. Нет таблицы `users2`, куда идет обращение при авторизации (https://github.com/parserpro/fantlab/issues/908)

**Comment by kenrube** [comment]
@Mazian 4 пункт выделил в две отдельных таски: https://github.com/FantLab/FantLab-Go/issues/52, https://github.com/FantLab/FantLab-Go/issues/53

**Comment by kenrube** [comment]
https://github.com/FantLab/FantLab-Go/pull/56
