### ISSUE TITLE
Настроить логирование ошибок с идентификатором

### ISSUE THREAD

**Issue by geor-kasapidi** [FantLab/FantLab-Go#78]
Это удобно при разборе инцидентов - к логу ошибки привязывается айди, который также отсылается клиенту. При наличии настроенной системы логов, при обращении в условный саппорт можно довольно легко выяснить проблему

**Comment by UncleAndy** [comment]
Я для похожего (запись лога запроса под уникальным идентификатором использую вот такой способ:

```go
err = http.ListenAndServe(Config.Listen.Address.String()+":"+strconv.FormatInt(int64(Config.Listen.Port), 10), http.HandlerFunc(logRequest))

...

func logRequest(w http.ResponseWriter, r *http.Request) {
	defer app.PanicHandle()

	rid := random.String(8)
	tprofile := app.TimeProfileCreate()
	app.Debug.Printf("START: [%s] %s %s %s\n", rid, r.RemoteAddr, r.Method, r.URL)
	http.DefaultServeMux.ServeHTTP(w, r)
	app.Debug.Printf(" DONE: [%s] %s %s %s (%s)\n", rid, r.RemoteAddr, r.Method, r.URL, tprofile.GlobalDuration().String())
}
```
Я тут больше это делал для отслеживания времени выполнения запросов в логе.

Вам, по идее, достаточно этот идентификатор запихнуть в `r` и использовать где захотите. В том числе и в глобальном логировании - что-бы в логе можно было быстро найти все записи, относящиеся к данному запросу.

**Comment by geor-kasapidi** [comment]
@UncleAndy ага, я примерно в том же ключе думал) только руки не дошли :)
