### ISSUE TITLE
Сообщения непроверенных юзеров видны всем

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-Go#79]
Сообщения должны быть только если выполнено любое из условий:
- юзер проверен (`approved`)
- текущий юзер - модератор
- текущий юзер - админ
- текущий юзер - автор сообщения

Это, кстати, приводит к интересному эффекту: на [этой странице](https://fantlab.ru/forum/forum9page1/topic8894page4) всего 19 сообщений вместо стандартных 20

**Comment by geor-kasapidi** [comment]
предлагаю проще - для непроверенных скрывать текст, мол на модерации

**Comment by kenrube** [comment]
Идея норм, но тогда вкупе с этим юзеру надо добавить флаг `is_approved`. Сейчас каждая выдача пилится с учетом того, чтоб в будущем ее можно было заюзать для фронта. И вот с точки зрения фронта проверка (без флага) будет выглядеть криво: если текста нет, то юзер на премодерации. А если учесть, что пустые сообщения бывают (когда есть только аттачи), то еще и логика ошибочная

**Comment by geor-kasapidi** [comment]
не проблема вроде - впилить в прото модель дополнительное поле и все дела

**Comment by geor-kasapidi** [comment]
тогда можно вообще текст сообщения не передавать на клиент, зная флажочек у юзера. Единственное не уверен что лучше - is_approved или is_unapproved 🧐

**Comment by kenrube** [comment]
Лучше все ж is_approved. Во-первых, совпадает с полем в базе, во-вторых, в случае удаленного юзера user будет реально пустой. Хотя, с другой стороны, это добавляет каждому юзеру целое поле, которое в 99% случаев true 🧐

**Comment by kenrube** [comment]
Будет исправлено в рамках https://github.com/FantLab/FantLab-Go/issues/49
